### ISSUE TITLE
1. Calculator

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/advanced_ruby#1]
- https://github.com/osifoanosike/advanced_ruby/tree/master/Calculator

**Comment by abhishekjain16** [comment]
Can we have better conditions for if else.
eg. instead of using (!operand1.to_s.match(/^\d+$/) && !operand2.to_s.match(/^\d+$/)) 
Try using !(operand1.to_s.match(/^\d+$/) || !operand2.to_s.match(/^\d+$/)).
Plus these validation can be extracted to a different method too.
eg. 
def valid_operand?(operand)
  operand.to_s.match(/^\d+$/)
end

**Comment by osifoanosike** [comment]
Fixed.
