### ISSUE TITLE
Dynamic Method Call.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/advanced_ruby#5]
https://github.com/osifoanosike/advanced_ruby/tree/master/DynamicMethodCall

**Comment by mkangia** [comment]
Osifo, i think you are not completely getting the requirements. The Exercise says:
1)Derive a class from String which defines a few methods on Strings, eg exclude? (opp of include).
2)From the command line, create an object of the new class and prompt for a method name to call on the object. Once the user enters the method name, execute it and display the results on the command line.

I see the first part is well done but the second point is not. I should be entering the method name while running the file. So in your example 1) it asks for the string 2) ask the method name to be called 3) ask for the argument to be passed. Here you would also need to handle if i enter a method name that is not present. The beauty of ruby here is that i can tell which method to call at run time and not pre defined. 
Let me know in case you are still confused here.

Plus, the exclude method can be optimised.. Do brain storm it.

**Comment by osifoanosike** [comment]
I've made the method calls dynamic, as well as optimized the code. Would love to ask some questions though.

**Comment by mkangia** [comment]
Osifo, Thats serves the requirements better. 

Lets try to bend it in a better way. For arguments is it possible i pass it with the function call itself. like 
exclude sub_string
instead of checking it separately for methods that need it.. so i can just pass the arguments like
method_name args1 args2 arg3

Let it raise exception if invalid number of arguments are passed, dont worry about that.

Lets re-prompt in case of blank submissions.

**Comment by osifoanosike** [comment]
Corrections effected
